export const ROUTES = {
  landing: "/home",
  signup: "/signup",
  signin: "/signin",
  dashboard: "/dashboard",
  courses: "/courses",
  courseDetails: "/courses/:courseId",
  lessons: "/lessons/:lessonId",
  assignments: "/assignments/:assignmentId",
  progress: "/progress",
  discussions: "/discussions",
  notifications: "/notifications",
  profile: "/profile",
  bookmarks: "/bookmarks",
  certifications: "/certifications",
  assignments: "/assignments",
  events: "/events",
  community: "/community",
  support: "/support",
  settings: "/settings",
};
